//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


namespace Duomo.Common.Lib.Xml
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:Duomo.Common.Interfaces.Ftp")]
    [System.Xml.Serialization.XmlRootAttribute("FtpInterfacesRoot", Namespace = "urn:Duomo.Common.Interfaces.Ftp", IsNullable = false)]
    public partial class FtpInterfacesListXmlType
    {

        private FtpInterfaceXmlType[] ftpInterfaceDefinitionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FtpInterface")]
        public FtpInterfaceXmlType[] FtpInterfaceDefinition
        {
            get
            {
                return this.ftpInterfaceDefinitionField;
            }
            set
            {
                this.ftpInterfaceDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:Duomo.Common.Interfaces.Ftp")]
    public partial class FtpInterfaceXmlType
    {

        private string serverAddressField;

        private string ftpServerIDField;

        /// <remarks/>
        public string ServerAddress
        {
            get
            {
                return this.serverAddressField;
            }
            set
            {
                this.serverAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FtpServerID
        {
            get
            {
                return this.ftpServerIDField;
            }
            set
            {
                this.ftpServerIDField = value;
            }
        }
    }
}