//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


namespace Duomo.Common.Lib.Xml
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:Duomo.Common.Types.Authentications")]
    [System.Xml.Serialization.XmlRootAttribute("AuthenticationsRoot", Namespace = "urn:Duomo.Common.Types.Authentications", IsNullable = false)]
    public partial class AuthenticationsXmlType
    {

        private DatabaseAuthenticationXmlType[][] databaseAuthenticationsField;

        private FtpAuthenticationXmlType[][] ftpAuthenticationsField;

        private OtherAuthenticationXmlType[][] otherAuthenticationsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DatabaseAuthentication", typeof(DatabaseAuthenticationXmlType), IsNullable = false)]
        public DatabaseAuthenticationXmlType[][] DatabaseAuthentications
        {
            get
            {
                return this.databaseAuthenticationsField;
            }
            set
            {
                this.databaseAuthenticationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FtpServerAuthentication", typeof(FtpAuthenticationXmlType), IsNullable = false)]
        public FtpAuthenticationXmlType[][] FtpAuthentications
        {
            get
            {
                return this.ftpAuthenticationsField;
            }
            set
            {
                this.ftpAuthenticationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Authentication", typeof(OtherAuthenticationXmlType), IsNullable = false)]
        public OtherAuthenticationXmlType[][] OtherAuthentications
        {
            get
            {
                return this.otherAuthenticationsField;
            }
            set
            {
                this.otherAuthenticationsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:Duomo.Common.Types.Authentications")]
    public partial class DatabaseAuthenticationXmlType : AuthenticationXmlType
    {

        private string databaseIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DatabaseID
        {
            get
            {
                return this.databaseIDField;
            }
            set
            {
                this.databaseIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherAuthenticationXmlType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FtpAuthenticationXmlType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DatabaseAuthenticationXmlType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:Duomo.Common.Types.Authentications")]
    public partial class AuthenticationXmlType
    {

        private string userNameField;

        private string passwordField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:Duomo.Common.Types.Authentications")]
    public partial class OtherAuthenticationXmlType : AuthenticationXmlType
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:Duomo.Common.Types.Authentications")]
    public partial class FtpAuthenticationXmlType : AuthenticationXmlType
    {

        private string ftpServerIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FtpServerID
        {
            get
            {
                return this.ftpServerIDField;
            }
            set
            {
                this.ftpServerIDField = value;
            }
        }
    }
}